### ISSUE TITLE
Pildikontroll

### ISSUE THREAD

**Issue by Kairo93** [musamees/school-php-mysql#2]
Pildi üleslaadimisel kontrolli tüüpi ka, kas on ikka pilt (jpg,png,gif).

**Comment by musamees** [comment]
[Fixed Issue #2](https://github.com/musamees/school-php-mysql/commit/379a842cd2df0f2ff0eef96948bae5507a0ed157)
Muutsin faili uploadimise tüübi pildiks ja teostan ka backend konrolli enne uploadi.
