### ISSUE TITLE
Kustutamise kontroll

### ISSUE THREAD

**Issue by Kairo93** [musamees/school-php-mysql#6]
Kustutamisel kontrolli kas user_id on ikka number.

**Comment by musamees** [comment]
Kas peaks sama tegema ka update puhul?

**Comment by Kairo93** [comment]
Jah

**Comment by musamees** [comment]
Hmm, arutasime siin kursuse kaaslasega ja tekkis selline küsimus, et mida annab juurde see, et ma kontrollin kas id on ikka number? Kuna tegemist on AUTO_INCREMENT väljaga, ei saa kasutaja sinna ise sisendit salvestada. Kui ta ei ole number, siis kuvatakse kasutajale errorit.

**Comment by Kairo93** [comment]
Tõsi, sel juhul sa saad andmebaasilt errori. Praktikas sellist lähenemist mitte kunagi ei tehta (tehakse siiski, aga ei tohi). Üldiselt kõik andmed mis sa andmebaasi pihta saadad (numbrid, tekst) peavad olema sinu poolt kontrollitud, et need valideeruvad. Näiteks kui tekstisisestus salvestatakse andmebaasi ja andmebaasi väli on varchar(32) siis pead kontrollima, et tekstisisestus ei oleks pikem kui 32 karakterit, mitte püüad seda mysql errorit. Näiteks production'is ei kuvatagi kasutajatele mysql erroreid, see põhjustab turvariski, keegi saab liiga palju teada andmebaasist ja teab paremini mida ja kuidas rünnata.

**Comment by musamees** [comment]
Selge.  Rääkisin samal teemal ka Kurmiga. Enne sinu vastuse nägemist ja ta rääkis sama juttu mida sinagi. Tänan, et võtsid aega ja vastasid :)
