### ISSUE TITLE
Tabel

### ISSUE THREAD

**Issue by Kairo93** [musamees/school-php-mysql#7]
Tabelit tehes saad ära märkida regdate ja lastupdate väljad automaatselt täidetuks. Siis sa ei pea enam läbi php midagi tegema. regdate default current_timestamp vms ja lastupdate default now() on update now() vms.

**Comment by musamees** [comment]
Lähtusin antud ülesannet lahendades Programmeerimine.pdf , Slide 15. 
Aga jah, sinu pakutud varjant tundub igati loogilisem. Viisin sisse parandused.

**Comment by musamees** [comment]
Viisin sisse muudatused.
